global:
  image: {}
  rollingUpdate: {}
  minions:
    image: {}

# image setting loadding order: (from higher priority to lower priority)
# - Values.image.x
# - Values.global.minions.image.x
# - Values.global.image.x
# - Values.defaultImage.x
# You can set `imagePullSecret` value to `false` (bool) to reset the value (see example below)

image: 
  name: "magda-minion-knowledge-graph"
  # repository: 
  # tag: 
  # pullPolicy: 
  # imagePullSecret: 

defaultImage:
  repository: docker.io/data61
  tag: 1.0.0
  pullPolicy: IfNotPresent
  imagePullSecret: false

defaultAdminUserId: "00000000-0000-4000-8000-000000000000"

resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 100m